### ISSUE TITLE
Priority error

### ISSUE THREAD

**Issue by thepandaknows** [thepandaknows/Check-It-2#7]
"Please select a task to edit before assigning priority" drop down appears upon clicking Save for a new task

**Comment by thepandaknows** [comment]
Fixed that, but the priority assignment sometimes adds to a row in the table

**Comment by GamesBrewing** [comment]
I think this issue is fixed. Can't replicate it anymore. 
This issue was solved by changing priorityComboBox_SelectedIndexChanged. Changed it to the following code:
private void priorityComboBox_SelectedIndexChanged(object sender, EventArgs e)
{
// check if an item is selected in the priority combo box
if (priorityComboBox.SelectedIndex != -1)
{
// retrieve the selected priority
string selectedPriority = priorityComboBox.SelectedItem.ToString();

            // update the priority of the task currently being edited
            if (isEditing)  //update selected cell
            { todoList.Rows[toDoListView.CurrentCell.RowIndex]["Priority"] = selectedPriority; 
            }
            priorityComboBox.SelectedItem = priorityComboBox.SelectedIndex;  // change priority box without changing last edited cell.
        } 
        else
        {
            MessageBox.Show("Please select a priority.");
        }
    }
